[package]
name = "pyrao"
version = "0.2.6"
edition = "2024"
description = "Python wrapper for rao rust package."
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyrao"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.2"
numpy = "0.28.0"
rao = "0.2.1"
serde = { version = "1.0.228", features = ["derive"] }
yaml_serde = "0.10.4"

[dependencies.pyo3]
version = "0.28.3"
features = ["abi3-py38","experimental-inspect"]

