[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "rao"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
authors = [
  { name="Jesse Cranney", email="jesse.cranney@anu.edu.au" },
]
description = "Python wrapper for RAO rust package"

[tool.maturin]
features = ["pyo3/extension-module"]
